import Head from 'next/head'
import Banner from "../components/Banner"
import Features from "../components/Features"
import Action from "../components/Action"
import Questions from "../components/Questions"
import Testimonals from "../components/Testimonals"
import Infographic from "../components/Infographic"
import Blog from "../components/Blog"

import {useEffect} from 'react'

export default function Home() {

  
  useEffect(() => {
    document.getElementById("contact").classList.remove("active");
    document.getElementById("about").classList.remove("active");
    document.getElementById("services").classList.remove("active");
    document.getElementById("gallery").classList.remove("active");

    
}, [])


  return (
    <div>
      <Head>
        <title>AFS Lojistik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner/>

      <Features/>

      <Questions/>
      
      <Action/>

      <Testimonals/>

      <Infographic/>

      <Blog/>

     
    </div>
  )
}
