import Head from 'next/head'
import Banner from "../components/Banner"
import Features from "../components/Features"
import Action from "../components/Action"
import Questions from "../components/Questions"
import Testimonals from "../components/Testimonals"
import Infographic from "../components/Infographic"
import Blog from "../components/Blog"



export default function Home() {



  return (
    <div>
      <Head>
        <title>Vercel Logistic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner/>

      <Features/>

      <Questions/>
      
      <Action/>

      <Testimonals/>

      <Infographic/>

      <Blog/>

     
    </div>
  )
}
